spring.application.name=petconnect-backend
# Change the server port to 8081
server.port=8081
# Enable pretty JSON output
spring.jackson.serialization.indent-output=true
# only update DB schema (keep existing data)
spring.jpa.hibernate.ddl-auto=update

## Use this config for MariaDB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# auth0 configuration
okta.oauth2.issuer=https://dev-py3uoa26xl8kkc35.us.auth0.com/
okta.oauth2.audience=https://petconnect.api