spring.application.name=petconnect-backend
# Change the server port to 8081
server.port=8081
# Enable pretty JSON output
spring.jackson.serialization.indent-output=true
# only update DB schema (keep existing data)
spring.jpa.hibernate.ddl-auto=update

## Use this config for MariaDB
spring.datasource.url=jdbc:mariadb://58ea917d-11a0-4864-979f-34a7070d9edc.ma.bw-cloud-instance.org:3307/petconnect-test
spring.datasource.username=petconnect1
spring.datasource.password=tUIo39tZtlwV6Y5y
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver